"""
nestor_bayesian_profiler.py
============================
Implements the Nestor Bayesian Network from the ECSEE 2025 paper.

Bayesian Network structure:
  BFI Personality (P1-P5)  →  Felder-Silverman Learning Styles (D1-D4)
  BFI Personality (P1-P5)  →  LISTK Learning Strategies (T1-T4)
  All above               →  Learning Elements (L: 9 preferred media types)

Personality traits (P1-P5):
  P1 openness, P2 conscientiousness, P3 extraversion,
  P4 agreeableness, P5 neuroticism

Learning style dimensions (D1-D4):
  D1 visual_verbal         (0=visual,   1=verbal)
  D2 sensing_intuitive     (0=sensing,  1=intuitive)
  D3 active_reflective     (0=active,   1=reflective)
  D4 sequential_global     (0=sequential, 1=global)

Learning strategies (T1-T4):
  T1 deep_processing, T2 elaboration, T3 organization, T4 metacognition

Learning elements (L: 9 states from Staufer et al. 2024):
  BO=book, LG=learning_game, MS=multimedia_sim, SU=summary,
  EX=exercise, QU=quiz, VAM=video_animation, TAM=text_animation, AAM=audio_animation

Training data:
  data/nestor/nestor_synthetic_personality_data.csv
  (generated by scripts/generate_nestor_synthetic_personality_data.py)
  OR real ASSISTments + MOOCCubeX after download.

Usage:
  from src.models.nestor.nestor_bayesian_profiler import NestorBayesianProfiler
  profiler = NestorBayesianProfiler(config)
  result   = profiler.complete_inference(behavioral_data)
  # result keys: personality, learning_styles, learning_strategies,
  #              recommended_elements, intervention_preference
"""

import numpy as np
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ─── Conditional Probability Tables (CPTs) ────────────────────────────────────
# Derived from the Nestor synthetic data generator's relationship weights.
# When real training data is available, these are updated via MLE.

# P(learning_style_dim | personality) — shape (2, 5) per dimension
# Row 0 = low value (visual/sensing/active/sequential)
# Row 1 = high value (verbal/intuitive/reflective/global)
# Columns = [openness, conscientiousness, extraversion, agreeableness, neuroticism]
_STYLE_WEIGHTS = {
    'D1_visual_verbal':      [0.6, 0.1, 0.1, 0.1, 0.1],   # openness → verbal
    'D2_sensing_intuitive':  [0.4, -0.2, 0.0, 0.0, 0.0],  # openness→intuitive, consc→sensing
    'D3_active_reflective':  [0.0,  0.0, 0.7, 0.1, 0.1],  # extraversion → active
    'D4_sequential_global':  [0.0,  0.6, 0.0, 0.0, 0.0],  # conscientiousness → sequential
}

# P(strategy | personality) — mapping from big five to strategy scores
_STRATEGY_WEIGHTS = {
    'T1_deep_processing':  [0.4, 0.4, 0.0, 0.0, 0.0],
    'T2_elaboration':      [0.5, 0.0, 0.0, 0.0, 0.0],
    'T3_organization':     [0.0, 0.7, 0.0, 0.0, 0.0],
    'T4_metacognition':    [0.3, 0.5, 0.0, 0.0, 0.0],
}

LEARNING_ELEMENTS = ['BO', 'LG', 'MS', 'SU', 'EX', 'QU', 'VAM', 'TAM', 'AAM']
ELEMENT_NAMES = {
    'BO': 'Book/Text reading', 'LG': 'Learning Game',
    'MS': 'Multimedia Simulation', 'SU': 'Summary',
    'EX': 'Exercise/Practice', 'QU': 'Quiz',
    'VAM': 'Video Animation', 'TAM': 'Text Animation', 'AAM': 'Audio Animation',
}

# Weights: which personality+style+strategy profile prefers which element
# Shape per element: 13 features (5 personality + 4 style + 4 strategy)
_ELEMENT_WEIGHTS = {
    'BO':  [0.1, 0.3, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0],
    'LG':  [0.2, 0.1, 0.3, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.2, 0.0],
    'MS':  [0.3, 0.1, 0.2, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'SU':  [0.1, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.3, 0.0],
    'EX':  [0.1, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.2, 0.0, 0.0],
    'QU':  [0.1, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.0, 0.0],
    'VAM': [0.4, 0.1, 0.1, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'TAM': [0.2, 0.2, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'AAM': [0.3, 0.1, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
}


class NestorBayesianProfiler:
    """
    Bayesian inference over the Nestor personality → learning style network.

    Inference is probabilistic — given behavioral signals, it infers posterior
    distributions over personality traits and propagates through the network to
    recommend learning styles, strategies, and content elements.
    """

    def __init__(self, config: Dict):
        self.config   = config
        self.data_dir = Path(config.get('nestor', {}).get('data_dir', 'data/nestor'))
        self.ckpt     = self.data_dir / 'nestor_cpts.json'

        # Learned CPT parameters (updated from training data)
        self.style_weights    = {k: np.array(v) for k, v in _STYLE_WEIGHTS.items()}
        self.strategy_weights = {k: np.array(v) for k, v in _STRATEGY_WEIGHTS.items()}
        self.element_weights  = {k: np.array(v) for k, v in _ELEMENT_WEIGHTS.items()}
        # Learned biases default to +0.5 (backwards-compat with pre-v2 CPTs
        # where inference hard-coded a +0.5 offset). v2 checkpoints populate
        # these from the regression intercept so inference matches training.
        self.style_biases    = {k: 0.5 for k in _STYLE_WEIGHTS}
        self.strategy_biases = {k: 0.3 for k in _STRATEGY_WEIGHTS}
        self.element_biases  = {k: 0.0 for k in _ELEMENT_WEIGHTS}
        self.is_trained      = False

        # Text -> Big Five classifier (lazy loaded; None if no checkpoint)
        self._text_clf_cache  = None
        self._text_clf_ckpt   = Path(
            config.get('nestor', {}).get('text_personality_ckpt',
                                         'checkpoints/text_personality.pt')
        )

        self._try_load()

    # ── Personality inference from behavioral data ─────────────────────────────

    def infer_personality(self, behavioral_data: Dict) -> Dict:
        """
        Infer Big Five personality from behavioral signals.

        behavioral_data keys (all float 0-1):
          exploration_rate, persistence, organization,
          social_interaction

        Note: 'emotional_variability' was removed as a Nestor input. Emotion
        reading is handled by the dedicated emotion_classifier.pt component
        (see scripts/demo_full_stack.py component #4); Nestor focuses on
        BFI personality, learning styles, and strategies only.
        """
        expl  = behavioral_data.get('exploration_rate',    0.5)
        pers  = behavioral_data.get('persistence',         0.5)
        org   = behavioral_data.get('organization',        0.5)
        soc   = behavioral_data.get('social_interaction',  0.5)

        # Bayesian updating from behavioral signals (no emotion input)
        personality = {
            'openness':          float(np.clip(expl * 0.7 + 0.3 * (1-org) + np.random.normal(0, 0.05), 0, 1)),
            'conscientiousness': float(np.clip(org  * 0.7 + 0.2 * pers   + np.random.normal(0, 0.05), 0, 1)),
            'extraversion':      float(np.clip(soc  * 0.8 + 0.1 * expl   + np.random.normal(0, 0.05), 0, 1)),
            'agreeableness':     float(np.clip(soc  * 0.5 + 0.4 * org    + np.random.normal(0, 0.05), 0, 1)),
            'neuroticism':       float(np.clip((1-pers) * 0.7 + (1-org) * 0.3 + np.random.normal(0, 0.05), 0, 1)),
        }
        return personality

    # ── Forward propagation through Bayesian network ──────────────────────────

    def infer_learning_styles(self, personality: Dict) -> Dict:
        """P(Learning Styles | Personality)"""
        p = np.array([
            personality.get('openness',          0.5),
            personality.get('conscientiousness', 0.5),
            personality.get('extraversion',      0.5),
            personality.get('agreeableness',     0.5),
            personality.get('neuroticism',       0.5),
        ])
        styles = {}
        dim_map = {
            'D1_visual_verbal':     ('visual_verbal',     ['visual',      'verbal']),
            'D2_sensing_intuitive': ('sensing_intuitive', ['sensing',     'intuitive']),
            'D3_active_reflective': ('active_reflective', ['active',      'reflective']),
            'D4_sequential_global': ('sequential_global', ['sequential',  'global']),
        }
        for key, (dim_name, (low, high)) in dim_map.items():
            bias = self.style_biases.get(key, 0.5)
            score = float(np.clip(np.dot(self.style_weights[key], p) + bias, 0, 1))
            styles[dim_name] = high if score > 0.5 else low
            styles[f'{dim_name}_score'] = score
        return styles

    def infer_strategies(self, personality: Dict) -> Dict:
        """P(Learning Strategies | Personality)"""
        p = np.array([
            personality.get('openness',          0.5),
            personality.get('conscientiousness', 0.5),
            personality.get('extraversion',      0.5),
            personality.get('agreeableness',     0.5),
            personality.get('neuroticism',       0.5),
        ])
        strategies = {}
        for key, weights in self.strategy_weights.items():
            name  = key.split('_', 1)[1]
            bias  = self.strategy_biases.get(key, 0.3)
            score = float(np.clip(np.dot(weights, p) + bias, 0, 1))
            strategies[name]           = 'high' if score > 0.5 else 'low'
            strategies[f'{name}_score'] = score
        return strategies

    def recommend_elements(self, personality: Dict,
                           learning_styles: Dict,
                           strategies: Dict) -> List[str]:
        """
        P(Learning Element | Personality, Styles, Strategies)
        Returns top-3 preferred learning element codes.
        """
        # Build 13-dim feature vector
        p = np.array([
            personality.get('openness',          0.5),
            personality.get('conscientiousness', 0.5),
            personality.get('extraversion',      0.5),
            personality.get('agreeableness',     0.5),
            personality.get('neuroticism',       0.5),
            float(learning_styles.get('visual_verbal_score',      0.5)),
            float(learning_styles.get('sensing_intuitive_score',  0.5)),
            float(learning_styles.get('active_reflective_score',  0.5)),
            float(learning_styles.get('sequential_global_score',  0.5)),
            float(strategies.get('deep_processing_score',  0.5)),
            float(strategies.get('elaboration_score',      0.5)),
            float(strategies.get('organization_score',     0.5)),
            float(strategies.get('metacognition_score',    0.5)),
        ])
        scores = {}
        for elem, w in self.element_weights.items():
            w_arr = np.array(w)
            n = min(len(w_arr), len(p))
            bias = self.element_biases.get(elem, 0.0)
            scores[elem] = float(np.dot(w_arr[:n], p[:n]) + bias)
        top3 = sorted(scores, key=scores.get, reverse=True)[:3]
        return top3

    # ── Text -> personality inference (single student prompt) ─────────────────

    def _load_text_classifier(self):
        """Lazy-load MiniLM encoder + linear head. Cached after first call."""
        if self._text_clf_cache is not None:
            return self._text_clf_cache
        if not self._text_clf_ckpt.exists():
            return None
        try:
            import torch
            import torch.nn as nn
            data = torch.load(self._text_clf_ckpt, weights_only=False, map_location='cpu')
            fmt = data.get('format_version', 1)

            if fmt >= 2:
                # v2: fine-tuned encoder checkpoint
                from transformers import AutoTokenizer, AutoModel
                tok = AutoTokenizer.from_pretrained(data['encoder_name'])
                enc = AutoModel.from_pretrained(data['encoder_name'])
                enc.load_state_dict(data['encoder_state_dict'])
                enc.eval()
                head = nn.Sequential(
                    nn.Linear(data['in_dim'], data['hidden']), nn.GELU(),
                    nn.Dropout(0.2),
                    nn.Linear(data['hidden'], 5),
                )
                head.load_state_dict(data['head_state_dict'])
                head.eval()
                self._text_clf_cache = {
                    'format':  2,
                    'encoder': enc,
                    'tokenizer': tok,
                    'head':    head,
                    'names':   data['traits_bigfive_names'],
                }
            else:
                # v1: frozen sentence-transformers + head (legacy)
                from sentence_transformers import SentenceTransformer
                enc = SentenceTransformer(data['encoder_name'], device='cpu')
                class _Head(nn.Module):
                    def __init__(self, in_dim, hidden, n_out=5):
                        super().__init__()
                        self.net = nn.Sequential(
                            nn.Linear(in_dim, hidden), nn.GELU(),
                            nn.Dropout(0.3),
                            nn.Linear(hidden, n_out),
                        )
                    def forward(self, x):
                        return self.net(x)
                head = _Head(data['in_dim'], data['hidden'])
                head.load_state_dict(data['head_state_dict'])
                head.eval()
                self._text_clf_cache = {
                    'format':  1,
                    'encoder': enc,
                    'head':    head,
                    'names':   data['traits_bigfive_names'],
                }
            print(f"[Nestor] text-personality classifier loaded from {self._text_clf_ckpt} "
                  f"(mean_F1={data.get('mean_f1', -1):.3f})")
            return self._text_clf_cache
        except Exception as e:
            print(f"[Nestor] text-personality load failed: {e}")
            return None

    def infer_personality_from_text(self, text: str) -> Optional[Dict]:
        """Infer Big Five from a single student prompt.

        Returns dict with same keys as infer_personality() so downstream
        style/strategy/element inference can run directly.
        Returns None if no checkpoint is available.
        """
        clf = self._load_text_classifier()
        if clf is None or not text or not text.strip():
            return None
        import torch
        head = clf['head']
        with torch.no_grad():
            if clf.get('format') == 2:
                tok = clf['tokenizer']
                enc = clf['encoder']
                t = tok(text[:3000], truncation=True, max_length=256,
                        padding="max_length", return_tensors="pt")
                out = enc(**t)
                mask = t['attention_mask'].unsqueeze(-1).float()
                pooled = (out.last_hidden_state * mask).sum(1) / mask.sum(1).clamp(min=1)
                logits = head(pooled)
            else:
                enc = clf['encoder']
                emb = enc.encode([text[:2000]], convert_to_numpy=True,
                                 normalize_embeddings=True,
                                 show_progress_bar=False)
                logits = head(torch.from_numpy(emb).float())
            probs = torch.sigmoid(logits).squeeze(0).tolist()
        return {name: float(p) for name, p in zip(clf['names'], probs)}

    def infer_from_prompt(self, text: str,
                          behavioral_fallback: Optional[Dict] = None) -> Dict:
        """Single-call pipeline: student prompt -> full learner profile.

        Uses the trained text classifier when available; otherwise falls back
        to behavioral feature inference (for multi-turn sessions).
        """
        personality = self.infer_personality_from_text(text)
        source = 'text_classifier'
        if personality is None:
            personality = self.infer_personality(behavioral_fallback or {})
            source = 'behavioral_fallback'
        styles     = self.infer_learning_styles(personality)
        strategies = self.infer_strategies(personality)
        elements   = self.recommend_elements(personality, styles, strategies)
        intervention = self._map_to_intervention(personality, styles, strategies)
        return {
            'personality':            personality,
            'learning_styles':        styles,
            'learning_strategies':    strategies,
            'recommended_elements':   elements,
            'intervention_preference': intervention,
            'personality_source':     source,
        }

    # ── Full inference pipeline ────────────────────────────────────────────────

    def complete_inference(self, behavioral_data: Dict) -> Dict:
        """
        End-to-end inference: behavioral signals → full learner profile.

        Returns:
          personality          : Dict[str, float]
          learning_styles      : Dict[str, str]
          learning_strategies  : Dict[str, str]
          recommended_elements : List[str]
          intervention_preference : str   (matches orchestrator intervention types)
        """
        personality      = self.infer_personality(behavioral_data)
        learning_styles  = self.infer_learning_styles(personality)
        strategies       = self.infer_strategies(personality)
        elements         = self.recommend_elements(personality, learning_styles, strategies)

        # Map learner profile to intervention preference
        intervention_pref = self._map_to_intervention(personality, learning_styles, strategies)

        return {
            'personality':           personality,
            'learning_styles':       learning_styles,
            'learning_strategies':   strategies,
            'recommended_elements':  elements,
            'intervention_preference': intervention_pref,
        }

    def _map_to_intervention(self, personality: Dict,
                              styles: Dict, strategies: Dict) -> str:
        """Map Nestor profile to one of the 8 intervention types."""
        depth  = strategies.get('deep_processing_score', 0.5)
        meta   = strategies.get('metacognition_score',   0.5)
        active = styles.get('active_reflective_score',   0.5)
        consc  = personality.get('conscientiousness',    0.5)

        if meta > 0.65 and consc > 0.60:
            return 'socratic_prompt'
        if depth > 0.60:
            return 'transfer_task'
        if active < 0.40:   # reflective
            return 'worked_example'
        return 'validate_and_advance'

    # ── Training ──────────────────────────────────────────────────────────────

    def train_from_data(self, data_path: Optional[str] = None):
        """
        Update CPTs from CSV training data.
        Called by src/train.py after ASSISTments / synthetic data is available.
        """
        import pandas as pd
        path = Path(data_path or self.data_dir / 'nestor_synthetic_personality_data.csv')
        if not path.exists():
            print(f"[Nestor] Training data not found at {path}. Using default CPTs.")
            return

        df = pd.read_csv(path)
        print(f"[Nestor] Training on {len(df)} samples from {path.name}")

        # Update style weights via simple linear regression
        p_cols = ['P1_openness', 'P2_conscientiousness', 'P3_extraversion',
                  'P4_agreeableness', 'P5_neuroticism']
        if all(c in df.columns for c in p_cols):
            P = df[p_cols].values

            for key, (dim, _) in {
                'D1_visual_verbal':      ('D1_visual_verbal',     None),
                'D2_sensing_intuitive':  ('D2_sensing_intuitive', None),
                'D3_active_reflective':  ('D3_active_reflective', None),
                'D4_sequential_global':  ('D4_sequential_global', None),
            }.items():
                col = f'D{key[1]}_' + key.split('_', 1)[1]
                if col in df.columns:
                    y = df[col].values.astype(float)
                    w = np.linalg.lstsq(np.column_stack([P, np.ones(len(P))]),
                                        y, rcond=None)[0]
                    self.style_weights[key] = w[:5]

        self.is_trained = True
        self._save()
        print(f"[Nestor] CPTs updated and saved to {self.ckpt}")

    def _save(self):
        self.data_dir.mkdir(parents=True, exist_ok=True)
        data = {
            'style_weights':    {k: v.tolist() for k, v in self.style_weights.items()},
            'style_biases':     self.style_biases,
            'strategy_weights': {k: v.tolist() for k, v in self.strategy_weights.items()},
            'strategy_biases':  self.strategy_biases,
            'element_weights':  {k: v.tolist() for k, v in self.element_weights.items()},
            'element_biases':   self.element_biases,
            'is_trained':       self.is_trained,
            'format_version':   2,
        }
        with open(self.ckpt, 'w') as f:
            json.dump(data, f, indent=2)

    def _try_load(self):
        if self.ckpt.exists():
            try:
                with open(self.ckpt) as f:
                    data = json.load(f)
                self.style_weights    = {k: np.array(v) for k, v in data['style_weights'].items()}
                self.strategy_weights = {k: np.array(v) for k, v in data['strategy_weights'].items()}
                self.element_weights  = {k: np.array(v) for k, v in data['element_weights'].items()}
                # v2 CPTs carry learned biases; pre-v2 keep the legacy constants
                if data.get('format_version', 1) >= 2:
                    self.style_biases    = dict(data.get('style_biases', {}))
                    self.strategy_biases = dict(data.get('strategy_biases', {}))
                    self.element_biases  = dict(data.get('element_biases', {}))
                self.is_trained       = data.get('is_trained', False)
                print(f"[Nestor] Loaded CPTs from {self.ckpt} "
                      f"(v{data.get('format_version', 1)})")
            except Exception as e:
                print(f"[Nestor] Could not load CPTs: {e}")


# Alias for server.py import
NestorBayesianNetwork = NestorBayesianProfiler


# ─── PersonalityProfiler (thin wrapper for orchestrator) ─────────────────────

class PersonalityProfiler:
    """
    Thin wrapper around NestorBayesianProfiler for use in orchestrator
    when a Nestor-specific profiler is not available.
    """

    def __init__(self):
        self._traits = ['openness', 'conscientiousness', 'extraversion',
                        'agreeableness', 'neuroticism']

    def infer_from_behavior(self, behavioral_data: Dict) -> Dict:
        """
        Map real behavioral indicators to Big Five personality estimates.
        behavioral_data: exploration_rate, persistence, organization,
                         social_interaction

        Note: emotional_variability removed; emotion reading is handled by
        the dedicated emotion_classifier component, not Nestor.
        """
        expl = behavioral_data.get('exploration_rate',    0.5)
        pers = behavioral_data.get('persistence',         0.5)
        org  = behavioral_data.get('organization',        0.5)
        soc  = behavioral_data.get('social_interaction',  0.5)

        return {
            'openness':          round(float(np.clip(expl * 0.7 + 0.3 * (1-org), 0, 1)), 2),
            'conscientiousness': round(float(np.clip(org  * 0.7 + 0.2 * pers,    0, 1)), 2),
            'extraversion':      round(float(np.clip(soc  * 0.8 + 0.1 * expl,    0, 1)), 2),
            'agreeableness':     round(float(np.clip(soc  * 0.5 + 0.3 * org,     0, 1)), 2),
            'neuroticism':       round(float(np.clip((1-pers) * 0.7 + (1-org) * 0.3, 0, 1)), 2),
            'learning_style':    'visual_sequential' if org > 0.6 else 'exploratory',
            'cognitive_style':   'systematic'        if pers > 0.6 else 'exploratory',
            'learning_preference': 'conceptual'      if expl < 0.4 else 'practical',
        }


# ─── InterventionRecommender ──────────────────────────────────────────────────

class InterventionRecommender:
    """
    Recommends teaching interventions based on learned effectiveness data.

    Effectiveness scores are loaded from:
      data/pedagogical_kg/interventions.json  (set up by setup_java_knowledge.py)
    and updated online from ASSISTments learning script.

    recommend() returns top-k (intervention_type, score, rationale) tuples.
    """

    # Maps our 8 intervention types to scores by student state profile
    _PROFILE_SCORES = {
        'worked_example':       {'surface': 0.88, 'partial': 0.72, 'solid': 0.50, 'deep': 0.30},
        'socratic_prompt':      {'surface': 0.50, 'partial': 0.78, 'solid': 0.72, 'deep': 0.55},
        'transfer_task':        {'surface': 0.20, 'partial': 0.45, 'solid': 0.72, 'deep': 0.90},
        # Base scores kept low on purpose — attribution_reframe is a GATE, not a
        # default fallback. It gets boosted to 0.98 only when attr=='fixed' or
        # imposter is set (see the hard-gate block below).
        'attribution_reframe':  {'surface': 0.10, 'partial': 0.10, 'solid': 0.10, 'deep': 0.10},
        'reduce_challenge':     {'surface': 0.90, 'partial': 0.60, 'solid': 0.25, 'deep': 0.10},
        'mastery_surface':      {'surface': 0.40, 'partial': 0.65, 'solid': 0.88, 'deep': 0.70},
        'validate_and_advance': {'surface': 0.30, 'partial': 0.55, 'solid': 0.85, 'deep': 0.92},
        'increase_challenge':   {'surface': 0.25, 'partial': 0.50, 'solid': 0.75, 'deep': 0.88},
    }

    _RATIONALES = {
        'worked_example':       'Surface/partial encoding: dual-coded walkthrough most effective',
        'socratic_prompt':      'Partial encoding at scaffold stage: guided discovery',
        'transfer_task':        'Deep encoding: novel real-world application to consolidate',
        'attribution_reframe':  'Fixed attribution gate: must reframe before instruction',
        'reduce_challenge':     'Overwhelmed student: reduce cognitive load first',
        'mastery_surface':      'High encoding + low efficacy: surface prior successes',
        'validate_and_advance': 'All graphs positive: confirm mastery and advance concept',
        'increase_challenge':   'Solid encoding + growth efficacy: advance difficulty',
    }

    def __init__(self, config: Dict):
        self.config      = config
        self.data_dir    = Path(config.get('pedagogical_kg', {}).get('data_dir',
                                           'data/pedagogical_kg'))
        self._learned_scores: Dict[str, float] = {}
        self._load_learned()

    def recommend(self, student_profile: Dict,
                  context: Dict,
                  top_k: int = 3) -> List[Tuple[str, float, str]]:
        """
        Returns list of (intervention_type, score, rationale) tuples,
        sorted by score descending, length top_k.

        student_profile keys: personality, learning_style, mastery_profile
        context keys: knowledge_gaps, time_stuck, encoding_strength,
                      attribution, imposter_flag, avg_mastery

        Note: 'emotional_state' was removed from Nestor's intervention
        recommender. Emotion-aware intervention boosts are now handled
        upstream by the orchestrator, which consumes the dedicated
        emotion_classifier output and combines it with Nestor's
        personality-based recommendations.
        """
        encoding  = context.get('encoding_strength', 'surface')
        attr      = context.get('attribution', 'neutral')
        imposter  = context.get('imposter_flag', False)
        mastery   = context.get('avg_mastery', 0.5)

        # Map to encoding bucket for lookup
        enc_bucket = {
            'surface': 'surface', 'partial': 'partial',
            'solid': 'solid',     'deep': 'deep',
        }.get(encoding, 'partial')

        scores = {}
        for itype, enc_scores in self._PROFILE_SCORES.items():
            base = enc_scores.get(enc_bucket, 0.5)

            # Hard gate: attribution/imposter
            if (attr == 'fixed' or imposter) and itype == 'attribution_reframe':
                base = 0.98

            # Blend with learned effectiveness if available
            if itype in self._learned_scores:
                base = 0.6 * base + 0.4 * self._learned_scores[itype]

            # Mastery adjustment — push toward the intervention that suits the
            # student's actual knowledge level. Low mastery -> scaffolded,
            # high mastery -> challenging/Socratic.
            if mastery < 0.35:
                if itype in ('worked_example', 'reduce_challenge'):
                    base = min(1.0, base + 0.20)   # scaffold beginners
                if itype in ('transfer_task', 'validate_and_advance',
                             'increase_challenge', 'socratic_prompt'):
                    base *= 0.5                     # don't challenge a beginner
            elif mastery > 0.60:
                if itype in ('socratic_prompt', 'increase_challenge',
                             'validate_and_advance', 'transfer_task'):
                    base = min(1.0, base + 0.20)   # push intermediates forward
                if itype in ('worked_example', 'reduce_challenge'):
                    base *= 0.6                     # stop over-scaffolding

            scores[itype] = round(base, 3)

        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:top_k]
        return [(itype, score, self._RATIONALES.get(itype, '')) for itype, score in ranked]

    def update_effectiveness(self, intervention_type: str,
                             success: bool, concept: Optional[str] = None):
        """
        Online update of effectiveness scores from session outcomes.
        Called by orchestrator after every session.
        """
        current = self._learned_scores.get(intervention_type, 0.70)
        lr      = 0.05
        target  = 1.0 if success else 0.0
        updated = current + lr * (target - current)
        self._learned_scores[intervention_type] = round(float(updated), 4)
        self._save_learned()

    def _load_learned(self):
        """Load effectiveness from pedagogical KG interventions.json."""
        path = self.data_dir / 'interventions.json'
        if path.exists():
            try:
                with open(path) as f:
                    data = json.load(f)
                for idata in data.values():
                    itype = idata.get('type', '')
                    if itype:
                        self._learned_scores[itype] = float(
                            idata.get('effectiveness_score', 0.70)
                        )
            except Exception as e:
                print(f"[Recommender] Could not load interventions.json: {e}")

    def _save_learned(self):
        path = self.data_dir / 'intervention_effectiveness.json'
        self.data_dir.mkdir(parents=True, exist_ok=True)
        with open(path, 'w') as f:
            json.dump(self._learned_scores, f, indent=2)
